name: 3D Contribution Calendar

on:
  schedule:
    - cron: '0 */6 * * *'
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          user: smirk-dev
          template: classic
          base: header, activity, community, repositories, metadata
          config_timezone: America/New_York
          config_display: large
          config_output: svg
          config_twemoji: yes
          config_padding: 0, 10
          filename: profile-3d-contrib/profile-gitblock.svg
          plugin_isocalendar: yes
          plugin_isocalendar_duration: full-year
          extras_css: |
            svg { background: transparent !important; }
            body { background: transparent !important; }
            .field { background: transparent !important; }
