name: Generate 3D Contribution Calendar

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:
  push:
    branches:
      - main
    paths-ignore:
      - "profile-3d-contrib/**"

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Generate 3D Contribution Files
        uses: yoshi389111/github-profile-3d-contrib@0.7.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          USERNAME: smirk-dev

      - name: Refresh profile-purple-animate.svg
        run: |
          cp profile-3d-contrib/profile-night-rainbow.svg profile-3d-contrib/profile-purple-animate.svg

      - name: Commit and push generated SVGs
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add profile-3d-contrib/*.svg
          git diff --staged --quiet || git commit -m "chore: update 3d contribution svg"
          git push